version: 2
updates:
  # JavaScript / TypeScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      dev-dependencies:
        dependency-type: "development"

  # The actions used inside .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
